<a href="https://colab.research.google.com/github/pedroManuelP/C-digos-em-Python/blob/main/Determinante_de_uma_matriz_de_forma_recursiva_usando_cofatores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def determinante(A):
  # Casos base
  if A.shape == (1,1):
    return A[0, 0] # determinante de 1x1
  elif (A.shape == (2,2)):
    return A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0] # determinante de 2x2

  maiorQtd = 0; maiorQtdCol = 0; maiorQtdLin = 0; lin = 0; col = 0
  for i in range(A.shape[0]):
    # procura qual a linha que tem mais zeros e quantos
    qtdZero = 0
    for j in range(A.shape[1]):
        if A[i, j] == 0:
            qtdZero += 1
    if qtdZero > maiorQtdLin:
      maiorQtdLin = qtdZero
      lin = i

  for i in range(A.shape[1]):
    # procura qual a coluna que tem mais zeros e quantos
    qtdZero = 0
    for j in range(A.shape[0]):
        if A[j, i] == 0:
            qtdZero += 1
    if qtdZero > maiorQtdCol:
      maiorQtdCol = qtdZero
      col = i

  maiorQtd = max(maiorQtdCol, maiorQtdLin)
  if maiorQtd == A.shape[0]:
    return 0 # se existe uma linha ou coluna composta somente de zeros, retorna 0

  if maiorQtd == maiorQtdLin:
    # se quem tem mais zeros for uma linha, encontra o determinante usando o teorema de Laplace
    sum = 0
    for i in range(A.shape[1]):
      # percorre todas as colunas da linha "lin"
      if(A[lin, i]) != 0:
        subA = np.delete(A, lin, axis=0) # remove a linha i
        subA = np.delete(subA, i, axis=1) # remove a coluna
        sum += A[lin, i]*cofator(subA, lin, i) # A[i,j]*Cofator de A[i,j]
  else:
    # se quem tem mais zeros for uma colina, encontra o determinante usando o teorema de Laplace
    sum = 0
    for i in range(A.shape[0]):
      # percorre todas as colunas da linha "lin"
      if(A[i, col]) != 0:
        subA = np.delete(A, i, axis=0) # remove a linha i
        subA = np.delete(subA, col, axis=1) # remove a coluna
        sum += A[i, col]*cofator(subA, i, col) # A[i,j]*Cofator de A[i,j]
  return sum

def cofator(A, i, j):
   detA = determinante(A)
   return ((-1)**(i+j))*detA

def posto(R):
  rank = 0;
  for i in range(R.shape[0]):
    # percorrendo todas as linhas para encontrar o determinante de cada submatriz
    for j in range(R.shape[1]):
      # percorrendo todas as colunas para encontrar o determinante de cada submatriz
      R_teste = R
      subR = np.zeros([rank+1, rank+1]) # submatriz de R para testar se o posto é maior que rank
      for l in range(0, (R.shape[0]-1)-rank):
        # percorrendo as linhas para retirar as linhas de R e formar a submatriz
        if(l != i):
          subR = np.delete(R_teste, l, axis=0) # remove a linha l
      for c in range(0, (R.shape[1]-1)-rank):
        # percorrendo as linhas para retirar as linhas de R e formar a submatriz
        if(c != j):
          subR = np.delete(R_teste, c, axis=1) # remove a coluna c
      print("subR: "+str(subR))
      if determinante(subR) != 0:
        rank += 1
  return rank

In [9]:

#A = np.array([[1, 2, 3, -3, 1],
#              [0, 4, 0, 0, 0],
#              [0, 1, 0, 1, 1],
#              [0, -6, 6, 1, 3],
#              [0, 2, 0, -1, 1]])

decimals = 0; n = 5; A = 10.*np.random.rand(n,n) - 5; A = np.round(A, decimals)
print("Matriz A:" + str(A))
print("Dimensão de A: " + str(A.shape))
print("Determinante de A usando numpy: " + str(round(np.linalg.det(A), decimals)))
print("Determinante de A usando a função determinante: " + str(round(determinante(A), decimals)))


Matriz A:[[ 2. -2.  1. -2.  4.]
 [ 3. -3. -3. -1. -4.]
 [ 0. -3. -4.  5.  0.]
 [ 0. -0. -4. -4.  2.]
 [ 4.  3. -2.  2.  4.]]
Dimensão de A: (5, 5)
Determinante de A usando numpy: 7450.0
Determinante de A usando a função determinante: 7450.0
